export const PROJECT_SUFFIX_LIB_DATA_MODEL = 'data-model';
export const PROJECT_SUFFIX_LIB_SHARED = 'shared';
export const PROJECT_SUFFIX_APP_CLI = 'cli';
export const PROJECT_SUFFIX_APP_BACKEND = 'be';
export const PROJECT_SUFFIX_APP_WEB = 'web';

export const ALL_PROJECT_SUFFIXES: readonly string[] = [
  PROJECT_SUFFIX_APP_WEB,
  PROJECT_SUFFIX_APP_BACKEND,
  PROJECT_SUFFIX_APP_CLI,
  PROJECT_SUFFIX_LIB_SHARED,
  PROJECT_SUFFIX_LIB_DATA_MODEL,
];
