version: '3.9'

services:
  mongodb:
    image: mongo:${MONGO_VERSION}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=user
#      - MONGO_INITDB_ROOT_PASSWORD=pass
