version: '3.9'

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
